#
# based on the work done by William at: https://github.com/William-Yeh/docker-enabled-vagrant
#
# $ vagrant init debian/jessie64; vagrant up --provider virtualbox

Vagrant.configure(2) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian/jessie64"

  # avoid possible request "vagrant@127.0.0.1's password:" when "up" and "ssh"
  config.ssh.password = "vagrant"

  config.vm.provision :shell, :path => "provision-script.sh"

  config.vm.define "vm-debian-docker"

  # IP address of the VM accessible from the computer host running it
  config.vm.network "private_network", ip: "192.168.42.42"
  config.vm.network :forwarded_port, guest: 6379, host: 9000 # to reach redis from outside: `telnet localhost 9000`
  for i in 8080..8089
    # forewarding ports to 1K above e.g. 8080 -> 9080
    config.vm.network :forwarded_port, guest: i, host: 1000+i
  end

  # Disabling the current folder from being shared inside the VM
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Sharing selected folders with the VM
  config.vm.synced_folder "../cache-redis-implementation", "/home/vagrant/components/cache-redis-implementation/"
  config.vm.synced_folder "../frontend-js-implementation", "/home/vagrant/components/frontend-js-implementation/"
  config.vm.synced_folder "../go-implementation", "/home/vagrant/components/go-implementation/"
  config.vm.synced_folder "../java-implementation", "/home/vagrant/components/java-implementation/"
  config.vm.synced_folder "../node-implementation", "/home/vagrant/components/node-implementation/"

end
